-- Seed file for local development
--
-- このファイルは `supabase db reset` だけでなく、CI の
-- `supabase db push --include-seed` からホスト環境の DB にも適用され得る。
-- そのため、固定の認証情報（admin ユーザー等）や環境固有のデータは
-- 絶対にここへ書かないこと。
--
-- ローカル開発用の admin ユーザー（admin@example.com）は
-- `pnpm seed`（`pnpm db:reset` からも実行される）が作成する。
-- 実装は packages/seed/shared/admin-user.ts を参照。
-- 接続先が localhost 以外の場合は作成をスキップするため、
-- ホスト環境の DB に固定パスワードのアカウントが作られることはない。
